// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestApp.DataAccess;

#nullable disable

namespace TestApp.DataAccess.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20240928150244_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TestApp.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Due")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2024, 9, 28, 20, 32, 43, 742, DateTimeKind.Local).AddTicks(7605),
                            Description = "Dis A",
                            Due = new DateTime(2024, 10, 3, 20, 32, 43, 742, DateTimeKind.Local).AddTicks(7627),
                            Status = 0,
                            Title = "Title A"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2024, 9, 28, 20, 32, 43, 742, DateTimeKind.Local).AddTicks(7637),
                            Description = "Dis B",
                            Due = new DateTime(2024, 10, 3, 20, 32, 43, 742, DateTimeKind.Local).AddTicks(7638),
                            Status = 0,
                            Title = "Title B"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
