// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestApp.DataAccess;

#nullable disable

namespace TestApp.DataAccess.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20240928162137_CreateAuthor")]
    partial class CreateAuthor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TestApp.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Author 1"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Author 2"
                        });
                });

            modelBuilder.Entity("TestApp.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Due")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Created = new DateTime(2024, 9, 28, 21, 51, 35, 778, DateTimeKind.Local).AddTicks(3018),
                            Description = "Dis A",
                            Due = new DateTime(2024, 10, 3, 21, 51, 35, 778, DateTimeKind.Local).AddTicks(3041),
                            Status = 0,
                            Title = "Title A"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            Created = new DateTime(2024, 9, 28, 21, 51, 35, 778, DateTimeKind.Local).AddTicks(3060),
                            Description = "Dis B",
                            Due = new DateTime(2024, 10, 3, 21, 51, 35, 778, DateTimeKind.Local).AddTicks(3062),
                            Status = 0,
                            Title = "Title B"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            Created = new DateTime(2024, 9, 28, 21, 51, 35, 778, DateTimeKind.Local).AddTicks(3066),
                            Description = "Dis C",
                            Due = new DateTime(2024, 10, 3, 21, 51, 35, 778, DateTimeKind.Local).AddTicks(3067),
                            Status = 0,
                            Title = "Title C"
                        });
                });

            modelBuilder.Entity("TestApp.Models.Todo", b =>
                {
                    b.HasOne("TestApp.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });
#pragma warning restore 612, 618
        }
    }
}
